### ISSUE TITLE
How can I disable "Enter Save Name" in Ren'Py games that I play?

### ISSUE THREAD

**Issue by gaveitatry2** [F95Sam/UnRen#6]
@F95Sam

So for a while, I've been wondering how to disable that annoying "Enter Save Name" prompt in some Ren'Py games.  If I'm lucky, the game will already have an option in Preferences to disable it.  But oftentimes, the game doesn't.  I finally got around to asking on F95, but I only got one response.  The person told me to edit the screens.rpy file.  He didn't tell me which line to edit, but I believed that I could figure out it.  Unfortunately, the game that I was playing called 'The Tyrant' did not have a screens.rpy file.  It did have a screens.rpyb file in the games/cache folder, but when I opened it up in Notepad ++ it was just a bunch of gibberish.  So I asked the same guy what I should do.  He told me to have a look at the UnRen tool and see if it will let me decompile the screens.rypb.  But as far as I can tell, it won't let me.  It only decompliles rpyc files and not rpyb ones.  So I'm not really sure where to go from here.  I just want to get rid of that "Enter Save Names" prompt because I save a lot and I don't like dealing with that prompt.

**Comment by madeddy** [comment]
This repo is unmaintained so i close this.
